version: 0.0
os: linux
files:
  - source: 2023/
    destination: /2023

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/build-client.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start-backend.sh
      timeout: 300
      runas: root
