

# Application specification for the ReactJS client
applications:

  - name: ReactJSClient
    version: 16.20.1
    os: linux
    hooks:
      BeforeInstall:
        - location: scripts/npm-install.sh
          timeout: 300
      ApplicationStart:
        - location: scripts/start-client.sh
          timeout: 300

# Application specification for the Flask backend
  - name: FlaskBackend
    version: 3.8.10
    os: linux
    hooks:
      BeforeInstall:
        - location: scripts/venv-activate.sh
          timeout: 300
      AfterInstall:
        - location: scripts/install-backend.sh
          timeout: 300
      ApplicationStart:
        - location: scripts/start-backend.sh
          timeout: 300
